import type { AppState } from '../types';

// Realistic demo data seeded for portfolio showcase.
// All dates are relative to 2026-05-15 (current demo date).
export const DEMO_STATE: AppState = {
  settings: {
    monthlyIncome: 12000,
    currency: 'SAR',
    darkMode: true,
    customCategories: [],
    categoryBudgets: {
      'Food & Dining': 1500,
      Shopping: 1000,
      Transportation: 600,
      'Bills & Utilities': 800,
      Entertainment: 500,
      'Health & Wellness': 400,
      Housing: 2000,
    },
    disabledDefaultCategories: [],
    usdToSarRate: 3.75,
  },

  incomes: [
    {
      id: 'inc-1',
      name: 'Main Salary',
      amount: 12000,
      type: 'Salary',
      frequency: 'Monthly',
      date: '2026-05-01',
      isRecurring: true,
    },
    {
      id: 'inc-2',
      name: 'Freelance Design Project',
      amount: 2800,
      type: 'Freelance',
      frequency: 'One-time',
      date: '2026-05-08',
      isRecurring: false,
      note: 'Brand identity for local startup',
    },
    {
      id: 'inc-3',
      name: 'ETF Dividend',
      amount: 920,
      type: 'Investment',
      frequency: 'One-time',
      date: '2026-04-15',
      isRecurring: false,
      note: 'Q1 2026 VOO dividend reinvestment',
    },
    {
      id: 'inc-4',
      name: 'Consulting — UX Audit',
      amount: 1500,
      type: 'Freelance',
      frequency: 'One-time',
      date: '2026-03-22',
      isRecurring: false,
      note: 'Two-day UX audit for fintech client',
    },
    {
      id: 'inc-5',
      name: 'Aramco Dividend',
      amount: 640,
      type: 'Investment',
      frequency: 'One-time',
      date: '2026-02-28',
      isRecurring: false,
      note: 'Annual dividend from Saudi Aramco position',
    },
  ],

  expenses: [
    // ── May 2026 ─────────────────────────────────────────────────
    { id: 'e01', amount: 318, category: 'Food & Dining',    date: '2026-05-14', note: 'Weekly groceries — Tamimi',         accountType: 'debit' },
    { id: 'e02', amount: 88,  category: 'Transportation',   date: '2026-05-13', note: 'Uber x3 + fuel top-up',            accountType: 'credit' },
    { id: 'e03', amount: 460, category: 'Shopping',         date: '2026-05-12', note: 'Clothing — H&M + Zara',            accountType: 'credit' },
    { id: 'e04', amount: 135, category: 'Entertainment',    date: '2026-05-11', note: 'Friday dinner out',                 accountType: 'credit' },
    { id: 'e05', amount: 660, category: 'Bills & Utilities',date: '2026-05-05', note: 'Electricity + internet + STC plan',accountType: 'debit' },
    { id: 'e06', amount: 220, category: 'Health & Wellness',date: '2026-05-03', note: 'Gym + protein supplements',        accountType: 'credit' },
    { id: 'e07', amount: 175, category: 'Food & Dining',    date: '2026-05-02', note: 'Work lunches x5',                  accountType: 'credit' },
    // ── April 2026 ───────────────────────────────────────────────
    { id: 'e08', amount: 295, category: 'Food & Dining',    date: '2026-04-28', note: 'Groceries + fruits',               accountType: 'debit' },
    { id: 'e09', amount: 1200,category: 'Housing',          date: '2026-04-25', note: 'Apartment maintenance & cleaning',  accountType: 'debit' },
    { id: 'e10', amount: 390, category: 'Shopping',         date: '2026-04-22', note: 'Headphones + accessories',         accountType: 'credit' },
    { id: 'e11', amount: 92,  category: 'Transportation',   date: '2026-04-20', note: 'Fuel x2 fill-ups',                 accountType: 'debit' },
    { id: 'e12', amount: 660, category: 'Bills & Utilities',date: '2026-04-05', note: 'Monthly bills bundle',             accountType: 'debit' },
    { id: 'e13', amount: 265, category: 'Entertainment',    date: '2026-04-18', note: 'Weekend Bahrain trip + Netflix',   accountType: 'credit' },
    { id: 'e14', amount: 320, category: 'Food & Dining',    date: '2026-04-10', note: 'Groceries + café visits',          accountType: 'debit' },
    { id: 'e15', amount: 200, category: 'Remittances',      date: '2026-04-01', note: 'Monthly family support',           accountType: 'debit' },
    // ── March 2026 ───────────────────────────────────────────────
    { id: 'e16', amount: 310, category: 'Food & Dining',    date: '2026-03-28', note: 'Weekly groceries',                 accountType: 'debit' },
    { id: 'e17', amount: 550, category: 'Shopping',         date: '2026-03-20', note: 'Spring wardrobe refresh',          accountType: 'credit' },
    { id: 'e18', amount: 660, category: 'Bills & Utilities',date: '2026-03-05', note: 'Monthly bills bundle',             accountType: 'debit' },
    { id: 'e19', amount: 155, category: 'Health & Wellness',date: '2026-03-15', note: 'Gym + doctor visit co-pay',        accountType: 'debit' },
    { id: 'e20', amount: 490, category: 'Travel',           date: '2026-03-10', note: 'Dubai long weekend — flights',     accountType: 'credit' },
    { id: 'e21', amount: 200, category: 'Remittances',      date: '2026-03-01', note: 'Monthly family support',           accountType: 'debit' },
    { id: 'e22', amount: 280, category: 'Food & Dining',    date: '2026-03-08', note: 'Groceries + iftar supplies',       accountType: 'debit' },
    // ── February 2026 ────────────────────────────────────────────
    { id: 'e23', amount: 270, category: 'Food & Dining',    date: '2026-02-25', note: 'Groceries',                        accountType: 'debit' },
    { id: 'e24', amount: 660, category: 'Bills & Utilities',date: '2026-02-05', note: 'Monthly bills bundle',             accountType: 'debit' },
    { id: 'e25', amount: 1800,category: 'Housing',          date: '2026-02-01', note: 'Quarterly apartment deep-clean + AC service', accountType: 'debit' },
    { id: 'e26', amount: 320, category: 'Shopping',         date: '2026-02-14', note: "Valentine's Day gifts",            accountType: 'credit' },
    { id: 'e27', amount: 200, category: 'Remittances',      date: '2026-02-01', note: 'Monthly family support',           accountType: 'debit' },
  ],

  goals: [
    {
      id: 'goal-1',
      name: 'Emergency Fund',
      targetAmount: 30000,
      currentAmount: 19500,
      date: '2026-12-31',
      note: '6 months of living expenses — priority goal',
      contributions: [
        { amount: 2000, date: '2026-05-01', note: 'Monthly contribution' },
        { amount: 2000, date: '2026-04-01', note: 'Monthly contribution' },
        { amount: 2000, date: '2026-03-01', note: 'Monthly contribution' },
        { amount: 2500, date: '2026-02-01', note: 'Bonus contribution' },
      ],
    },
    {
      id: 'goal-2',
      name: 'New Car — Land Cruiser',
      targetAmount: 80000,
      currentAmount: 25000,
      date: '2027-06-30',
      note: 'Saving for a Toyota Land Cruiser (2027 model)',
      contributions: [
        { amount: 3000, date: '2026-05-01', note: 'Monthly' },
        { amount: 3000, date: '2026-04-01', note: 'Monthly' },
        { amount: 3000, date: '2026-03-01', note: 'Monthly' },
        { amount: 3000, date: '2026-02-01', note: 'Monthly' },
      ],
    },
    {
      id: 'goal-3',
      name: 'Japan Trip 🇯🇵',
      targetAmount: 16000,
      currentAmount: 7600,
      date: '2026-11-30',
      note: 'Tokyo + Kyoto + Osaka — 10 days',
      contributions: [
        { amount: 1200, date: '2026-05-05', note: 'Monthly' },
        { amount: 1200, date: '2026-04-05', note: 'Monthly' },
        { amount: 1200, date: '2026-03-05', note: 'Monthly' },
        { amount: 2000, date: '2026-02-05', note: 'Freelance bonus allocation' },
      ],
    },
    {
      id: 'goal-4',
      name: 'MacBook Pro M5',
      targetAmount: 9000,
      currentAmount: 9000,
      date: '2026-04-30',
      note: 'Completed! Purchased April 2026.',
      contributions: [
        { amount: 9000, date: '2026-04-10', note: 'Full purchase — saved up' },
      ],
    },
  ],

  investments: [
    // ── S&P 500 ETF (VOO) — two lots ─────────────────────────────
    {
      id: 'lot-1',
      positionKey: 'voo',
      name: 'Vanguard S&P 500 ETF',
      ticker: 'VOO',
      category: 'ETFs',
      quantity: 14,
      pricePerUnit: 478,
      unitType: 'shares',
      purchaseCurrency: 'USD',
      date: '2025-11-10',
      notes: 'Core long-term holding',
    },
    {
      id: 'lot-2',
      positionKey: 'voo',
      name: 'Vanguard S&P 500 ETF',
      ticker: 'VOO',
      category: 'ETFs',
      quantity: 10,
      pricePerUnit: 492,
      unitType: 'shares',
      purchaseCurrency: 'USD',
      date: '2026-02-20',
      notes: 'DCA — monthly contribution',
    },
    // ── NVIDIA ────────────────────────────────────────────────────
    {
      id: 'lot-3',
      positionKey: 'nvda',
      name: 'NVIDIA Corporation',
      ticker: 'NVDA',
      category: 'Stocks',
      quantity: 30,
      pricePerUnit: 790,
      unitType: 'shares',
      purchaseCurrency: 'USD',
      date: '2025-10-15',
      notes: 'AI infrastructure growth play',
    },
    // ── Saudi Aramco ──────────────────────────────────────────────
    {
      id: 'lot-4',
      positionKey: 'aramco',
      name: 'Saudi Aramco',
      ticker: '2222.SR',
      category: 'Stocks',
      quantity: 600,
      pricePerUnit: 27.8,
      unitType: 'shares',
      purchaseCurrency: 'SAR',
      date: '2025-12-05',
      notes: 'Local equity — dividend yield focus',
    },
    // ── Physical Gold ─────────────────────────────────────────────
    {
      id: 'lot-5',
      positionKey: 'gold-24k',
      name: '24K Gold',
      category: 'Gold/Commodities',
      quantity: 62,
      pricePerUnit: 272,
      unitType: 'grams',
      date: '2026-01-20',
      notes: 'Inflation hedge — physical bars stored at SABB',
      useManualValuation: true,
      manualCurrentValue: 19220,
    },
    // ── Crypto ────────────────────────────────────────────────────
    {
      id: 'lot-6',
      positionKey: 'btc',
      name: 'Bitcoin',
      ticker: 'BTC-USD',
      category: 'Crypto',
      quantity: 0.08,
      pricePerUnit: 68000,
      unitType: 'coins',
      purchaseCurrency: 'USD',
      date: '2026-03-14',
      notes: 'Small speculative position — max 5% of portfolio',
    },
  ],

  priceCache: {
    VOO: {
      price: 508.42,
      currency: 'USD',
      lastUpdated: '2026-05-15T08:00:00Z',
      source: 'demo',
    },
    NVDA: {
      price: 924.80,
      currency: 'USD',
      lastUpdated: '2026-05-15T08:00:00Z',
      source: 'demo',
    },
    'BTC-USD': {
      price: 96400,
      currency: 'USD',
      lastUpdated: '2026-05-15T08:00:00Z',
      source: 'demo',
    },
  },
};
